// Code generated by goctl. DO NOT EDIT!
// Source: video.proto

package server

import (
	"context"
	logic2 "tiktok/video/rpc/internal/logic"
	"tiktok/video/rpc/internal/svc"
	video2 "tiktok/video/rpc/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video2.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) PublishVideo(ctx context.Context, in *video2.PublishVideoReq) (*video2.PublishVideoResp, error) {
	l := logic2.NewPublishVideoLogic(ctx, s.svcCtx)
	return l.PublishVideo(in)
}

func (s *VideoServer) PublishVideoList(ctx context.Context, in *video2.PublishVideoListReq) (*video2.PublishVideoListResp, error) {
	l := logic2.NewPublishVideoListLogic(ctx, s.svcCtx)
	return l.PublishVideoList(in)
}
