// Code generated by goctl. DO NOT EDIT!
// Source: like.proto

package server

import (
	"context"

	"tiktok/like/rpc/internal/logic"
	"tiktok/like/rpc/internal/svc"
	"tiktok/like/rpc/like"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	like.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) LikeVideo(ctx context.Context, in *like.LikeVideoReq) (*like.LikeVideoResp, error) {
	l := logic.NewLikeVideoLogic(ctx, s.svcCtx)
	return l.LikeVideo(in)
}
