// Code generated by goctl. DO NOT EDIT!
// Source: like.proto

package likeclient

import (
	"context"

	"tiktok/like/rpc/like"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LikeVideoReq  = like.LikeVideoReq
	LikeVideoResp = like.LikeVideoResp

	Like interface {
		LikeVideo(ctx context.Context, in *LikeVideoReq, opts ...grpc.CallOption) (*LikeVideoResp, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

func (m *defaultLike) LikeVideo(ctx context.Context, in *LikeVideoReq, opts ...grpc.CallOption) (*LikeVideoResp, error) {
	client := like.NewLikeClient(m.cli.Conn())
	return client.LikeVideo(ctx, in, opts...)
}
