// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likesFieldNames          = builder.RawFieldNames(&Likes{})
	likesRows                = strings.Join(likesFieldNames, ",")
	likesRowsExpectAutoSet   = strings.Join(stringx.Remove(likesFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	likesRowsWithPlaceHolder = strings.Join(stringx.Remove(likesFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheDouyinLikesIdPrefix            = "cache:douyin:likes:id:"
	cacheDouyinLikesUserIdVideoIdPrefix = "cache:douyin:likes:userId:videoId:"
)

type (
	likesModel interface {
		Insert(ctx context.Context, data *Likes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Likes, error)
		FindOneByUserIdVideoId(ctx context.Context, userId int64, videoId int64) (*Likes, error)
		Update(ctx context.Context, data *Likes) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLikesModel struct {
		sqlc.CachedConn
		table string
	}

	Likes struct {
		Id      int64 `db:"id"`       // 自增主键
		UserId  int64 `db:"user_id"`  // 点赞用户id
		VideoId int64 `db:"video_id"` // 被点赞的视频id
		Cancel  int64 `db:"cancel"`   // 默认点赞为1，取消赞为0
	}
)

func newLikesModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultLikesModel {
	return &defaultLikesModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`likes`",
	}
}

func (m *defaultLikesModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	douyinLikesIdKey := fmt.Sprintf("%s%v", cacheDouyinLikesIdPrefix, id)
	douyinLikesUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheDouyinLikesUserIdVideoIdPrefix, data.UserId, data.VideoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, douyinLikesIdKey, douyinLikesUserIdVideoIdKey)
	return err
}

func (m *defaultLikesModel) FindOne(ctx context.Context, id int64) (*Likes, error) {
	douyinLikesIdKey := fmt.Sprintf("%s%v", cacheDouyinLikesIdPrefix, id)
	var resp Likes
	err := m.QueryRowCtx(ctx, &resp, douyinLikesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) FindOneByUserIdVideoId(ctx context.Context, userId int64, videoId int64) (*Likes, error) {
	douyinLikesUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheDouyinLikesUserIdVideoIdPrefix, userId, videoId)
	var resp Likes
	err := m.QueryRowIndexCtx(ctx, &resp, douyinLikesUserIdVideoIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `video_id` = ? limit 1", likesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, videoId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) Insert(ctx context.Context, data *Likes) (sql.Result, error) {
	douyinLikesIdKey := fmt.Sprintf("%s%v", cacheDouyinLikesIdPrefix, data.Id)
	douyinLikesUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheDouyinLikesUserIdVideoIdPrefix, data.UserId, data.VideoId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, likesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.VideoId, data.Cancel)
	}, douyinLikesIdKey, douyinLikesUserIdVideoIdKey)
	return ret, err
}

func (m *defaultLikesModel) Update(ctx context.Context, newData *Likes) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	douyinLikesIdKey := fmt.Sprintf("%s%v", cacheDouyinLikesIdPrefix, data.Id)
	douyinLikesUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheDouyinLikesUserIdVideoIdPrefix, data.UserId, data.VideoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, likesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.VideoId, newData.Cancel, newData.Id)
	}, douyinLikesIdKey, douyinLikesUserIdVideoIdKey)
	return err
}

func (m *defaultLikesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDouyinLikesIdPrefix, primary)
}

func (m *defaultLikesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLikesModel) tableName() string {
	return m.table
}
